phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install yarn
      - yarn
      - yarn add eslint-config-react-app
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'