version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install 
  build:
    commands:
      - npm run-script build 

artifacts:
  files:
    - '**/*'
  base-directory: 'build'